jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
  - task: MSBuild@1
    displayName: Build solution **/*.cdsproj
    inputs:
      solution: '**/*.cdsproj'
      msbuildArguments: '/t:build /restore '
  - task: PowerPlatformToolInstaller@2
    displayName: 'Power Platform Tool Installer '
  - task: PowerPlatformSetConnectionVariables@2
    name: connectionVariables
    inputs:
      authenticationType: 'PowerPlatformSPN'
      PowerPlatformSPN: 'PowerPlatformTeide'
  - task: PowerShell@2
    retryCountOnTaskFailure: 10
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "ApplicationId: $(connectionVariables.BuildTools.ApplicationId)"
        Write-Host "TenantId: $(connectionVariables.BuildTools.TenantId)"
        Write-Host "EnvironmentURL: $(connectionVariables.BuildTools.EnvironmentUrl)"
    displayName: 'Invoke HTTP Request and loop'