jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
  - task: MSBuild@1
    displayName: Build solution **/*.cdsproj
    inputs:
      solution: '**/*.cdsproj'
      msbuildArguments: '/t:build /restore '
  - task: PowerPlatformToolInstaller@2
    displayName: 'Power Platform Tool Installer '
  - task: PowerPlatformImportSolution@2
    inputs:
      authenticationType: 'PowerPlatformSPN'
      PowerPlatformSPN: 'PowerPlatformTeide'
      Environment: '$(environmentUrl)'
      SolutionInputFile: '$(solutionName)\bin\Debug\$(solutionName).zip'
      AsyncOperation: true
      MaxAsyncWaitTime: '60'
  - task: AzureCLI@2
    name: setVariables
    displayName: Set Output Variables
    continueOnError: false
    inputs:
      azureSubscription: PowerPlatformTeide
      scriptType: ps
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      inlineScript: |
        Write-Host "##vso[task.setvariable variable=appId;isOutput=true]$($env:servicePrincipalId)"
        Write-Host "##vso[task.setvariable variable=clientSecret;isOutput=true]$($env:servicePrincipalKey)"
        Write-Host "##vso[task.setvariable variable=tenantId;isOutput=true]$($env:tenantId)"
  - task: PowerShell@2
    retryCountOnTaskFailure: 10
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)\http_requests.ps1
    displayName: 'Invoke HTTP Request and loop'
    env:
      appId: $(setVariables.appId)
      clientSecret: $(setVariables.clientSecret)
      tenantId: $(setVariables.tenantId)