jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
  - task: PowerShell@2
    retryCountOnTaskFailure: 10
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)\http_requests.ps1
    displayName: 'Invoke HTTP Request and loop'