name: export-unpack-commit-solution
# Export solution from DEV environment
#  unpack it, commit and push the changes

on:
  workflow_dispatch:

jobs:
  export-from-dev:
    environment: DEV
    runs-on: ubuntu-latest

    env:
      source_branch: main
      commit_message: "initial commit"
      solution_export_folder: solution-export-temp
      solution_package_source: "src/${{ secrets.SOLUTION_NAME }}/SolutionPackage"
      branch_to_create: "${{ secrets.BRANCH_TO_CREATE }}"

    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "branch_to_create: ${{ env.branch_to_create }}"
          echo "solution_package_source: ${{ env.solution_package_source }}"
          echo "solution_export_folder: ${{ env.solution_export_folder }}"
          