name: export-unpack-commit-solution
# Export solution from DEV environment
#  unpack it, commit and push the changes

on:
  workflow_dispatch:

jobs:
  export-from-dev:
    environment: DEV
    runs-on: ubuntu-latest

    env:
      source_branch: main
      commit_message: "initial commit"
      solution_export_folder: solution-export-temp
      solution_package_source: "src/${{ secrets.SOLUTION_NAME }}/SolutionPackage"
      branch_to_create: "${{ secrets.BRANCH_TO_CREATE }}"

    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "branch_to_create: ${{ env.branch_to_create }}"
          echo "solution_package_source: ${{ env.BRANCH_TO_CREATE }}"
          echo "solution_export_folder: ${{ env.solution_export_folder }}"
      # Solutions cannot be exported/imported in parallel, so we queue
      - uses: ahmadnassri/action-workflow-queue@v1

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.source_branch }}

      # Until GitHub Actions for Power Platform doesn't require us to use pac direcly
      # for certain commands, we need to use it directly.  So we set the path to pac
      # that ships with the Actions
      - name: set-pac-path
        uses: ./.github/actions/set-pac-path

      - name: create new git branch
        if: env.branch_to_create != ''
        run: |
          git checkout -b ${{ env.BRANCH_TO_CREATE }} ${{ github.event.inputs.source_branch }}
      # - name: publish customizations
      #   uses: microsoft/powerplatform-actions/publish-solution@v0
      #   with:
      #     environment-url: ${{ secrets.ENVIRONMENT_URL}}
      #     app-id: ${{ secrets.CLIENT_ID }}
      #     client-secret: ${{ secrets.CLIENT_SECRET }}
      #     tenant-id: ${{ secrets.TENANT_ID }}

      - name: export-unmanaged-solution
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url: ${{ secrets.ENVIRONMENT_URL}}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-name: ${{ secrets.SOLUTION_NAME }}
          solution-output-file: ${{ runner.temp }}/${{ env.solution_export_folder }}/${{ secrets.SOLUTION_NAME }}.zip
          managed: false

      - name: export-managed-solution
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url: ${{ secrets.ENVIRONMENT_URL}}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-name: ${{ secrets.SOLUTION_NAME }}
          solution-output-file: ${{ runner.temp }}/${{ env.solution_export_folder }}/${{ secrets.SOLUTION_NAME }}_managed.zip
          managed: true

      - name: unpack-solution action
        uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
          solution-file: ${{ runner.temp }}/${{ env.solution_export_folder }}/${{ secrets.SOLUTION_NAME }}.zip
          solution-folder: ${{ env.solution_package_source }}
          solution-type: "Both"
          overwrite-files: true

      - name: clear out solution version number
        shell: pwsh
        run: |
          Get-ChildItem -Path "${{ env.solution_package_source }}/**/Solution.xml" | 
          ForEach-Object {
                (Get-Content $_.FullName) `
                    -replace '<Version>[\s\S]*?<\/Version>', '<Version>0.0.0.0</Version>' |
                Out-File $_.FullName
          }
      - name: unpack msapp files
        shell: pwsh
        run: |
          Get-ChildItem -Path "${{ env.solution_package_source }}/CanvasApps" -Recurse -Filter *.msapp | 
          ForEach-Object {
              $unpackedPath = $_.FullName.Replace(".msapp", "_msapp_src")
              pac canvas unpack --msapp $_.FullName --sources $unpackedPath
              del $_.FullName
          }
      # TEMPORARY until platform/tools support formatted json files on unpack we
      # update the Power Automate json files to be pretty-print / formatted so they are easier to read in source control.
      # This also makes it easier to read changes from one commit to another
      - name: format json files
        shell: pwsh
        run: |
          Get-ChildItem -Path "${{ env.solution_package_source }}/Workflows" -Recurse -Filter *.json | 
          ForEach-Object {
            Write-Host $_.FullName
            $formatted = jq . $_.FullName --sort-keys
            $formatted | Out-File $_.FullName -Encoding UTF8
          }
      - name: commit changes
        run: |
          git config --global user.name ${{ github.actor }}   
          git add --all
          git commit -am "${{ github.event.inputs.commit_message }}"
      - name: push to ${{ github.event.inputs.source_branch }}
        if: env.BRANCH_TO_CREATE == ''
        run: |
          git push
      - name: push to ${{ env.BRANCH_TO_CREATE }}
        if: env.BRANCH_TO_CREATE != ''
        run: |
          git push --set-upstream origin ${{ env.BRANCH_TO_CREATE }}
