name: run-test-tool

on:
  workflow_dispatch:
    inputs:
      parameters:
        required: true
        description: "parameters"

jobs:
  run-test-tool:
    runs-on: windows-latest
    name: test
    steps:
        - uses: actions/checkout@v2

        - name: Execute bot test
          shell: cmd
          run: |
            cd tool
            TestBot.exe "${{ github.event.inputs.parameters }}"