name: run-test-tool

on:
  workflow_dispatch:
    inputs:
      userName:
        required: true
        description: "userName"
      greeting:
        required: true
        description: "greeting"

jobs:
  run-test-tool:
    runs-on: windows-latest
    name: test
    steps:
        - uses: actions/checkout@v2

        - name: Execute bot test
          shell: cmd
          run: |
            cd tool
            "${--greeting { github.event.inputs.userName }}" CommandLineApp.exe "${{ github.event.inputs.userName }}"