name: run-test-tool

on:
  workflow_dispatch:
    inputs:
      botName:
        required: true
        description: "Bot Name"
      botId:
        required: false
        description: "Bot Id"
      fileName:
        required: true
        description: "File name"

jobs:
  run-test-tool:
    runs-on: windows-latest
    name: test
    steps:
        - name: step_1
          shell: cmd
          run: |
            ./tool/TestBot.exe
            echo "${{ github.event.inputs.botName }}"

