name: run-test-tool

on:
  workflow_dispatch:
    inputs:
      userName:
        required: false
        description: "userName"
      greeting:
        required: false
        description: "greeting"

jobs:
  run-test-tool:
    runs-on: ubuntu-latest
    name: test
    steps:
        - uses: actions/checkout@v2

        - name: Make app executable
          run: chmod +x ./tool/CommandLineApp
        - name: Execute bot test
          shell: bash
          run: ./tool/CommandLineApp "${{ github.event.inputs.userName }}" --greeting "${{ github.event.inputs.greeting }}" -v