name: run-test-tool

on:
  workflow_dispatch:
    inputs:
      userName:
        required: false
        description: "userName"
      greeting:
        required: false
        description: "greeting"

jobs:
  run-test-tool:
    runs-on: ubuntu-latest
    name: test
    steps:
        - uses: actions/checkout@v2

        - name: Execute bot test
          shell: bash
          run: ls