name: pva-workflow
on:
  workflow_dispatch:

jobs:
  export-unpack-commit-solution:
    runs-on: ubuntu-latest
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "branch_to_create: ${{ env.branch_to_create }}"
          echo "solution_package_source: ${{ env.solution_package_source }}"
          echo "solution_export_folder: ${{ env.solution_export_folder }}"

  sync-unmanaged-solution:
    runs-on: ubuntu-latest
    needs: export-unpack-commit-solution
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "branch_to_create: ${{ env.branch_to_create }}"
          echo "solution_package_source: ${{ env.solution_package_source }}"
          echo "solution_export_folder: ${{ env.solution_export_folder }}"

  delete-and-import-unmanaged-solution:
    runs-on: ubuntu-latest
    needs: sync-unmanaged-solution
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "branch_to_create: ${{ env.branch_to_create }}"
          echo "solution_package_source: ${{ env.solution_package_source }}"
          echo "solution_export_folder: ${{ env.solution_export_folder }}"

  create-pr-with-solution:
    runs-on: ubuntu-latest
    needs: delete-and-import-unmanaged-solution
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "branch_to_create: ${{ env.branch_to_create }}"
          echo "solution_package_source: ${{ env.solution_package_source }}"
          echo "solution_export_folder: ${{ env.solution_export_folder }}"