name: pva-workflow
on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: "name of the Solution in Dataverse environment"
        required: true
        default: MicaSolution
      environment_url:
        description: "http endpoint of your Dataverse environment"
        required: true
        default: "https://orgea394ded.crm.dynamics.com/"
      source_branch:
        description: "source branch"
        required: true
        default: main
      branch_to_create:
        description: "branch to create"
        required: false
        default: "init2"
      commit_message:
        description: "message to provide for the commit"
        required: true
        default: "init message"
env:
  workflow_scripts_path: .github/workflows/scripts

jobs:
  export-unpack-commit-solution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      #- name: exec-export-unpack-commit-solution-workflow
      #  id: exec-export-unpack-commit-solution-workflow
      #  uses: actions/github-script@v5
      #  with:
      #    github-token: ${{secrets.WORKFLOW_DISPATCH_TOKEN}}
      #    script: |
      #      await github.rest.actions.createWorkflowDispatch({
      #        owner: context.repo.owner,
      #        repo: context.repo.repo,
      #        workflow_id: 'export-unpack-commit-solution.yml',
      #        ref: '${{ github.ref }}',
      #        inputs: {
      #          solution_name: '${{ github.event.inputs.solution_name }}',
      #          environment_url: '${{ github.event.inputs.environment_url }}',
      #          source_branch: '${{ github.event.inputs.source_branch }}',
      #          branch_to_create: '${{ github.event.inputs.branch_to_create }}',
      #          commit_message: '${{ github.event.inputs.commit_message }}'
      #        }
      #      })

      - name: Sleep for 5 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'

      - name: check-workflow-status
        id: check-workflow-status
        uses: actions/github-script@v5
        with:
          script: |
            let test = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'export-unpack-commit-solution.yml',
              per_page: 1
            })

            console.log('init')
            const sleep = require('${{ env.workflow_scripts_path }}/js/test.js')
            sleep(3000)
            console.log('end')
            console.log(test.data.total_count)
            if (test.data.total_count != 0) {
              let time = Date.now()
              
                console.log(test.data.workflow_runs[0].status)
                console.log(test.data.workflow_runs[0].conclusion)
                console.log(time)
              
            }
