name: trigger-determine-solution
on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: "name of the Solution in Dataverse environment"
        required: true
        default: MicaSolution
  pull_request:
    branches:
      - main
    paths:
      - src/**
  push:
    branches:
      - main
    paths:
      - src/**
  
        
env:
  workflow_scripts_path: .github/workflows/scripts


jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - name: test2
      uses: actions/github-script@v5
      with:
        script: |
            const runWorkflow = require('${{ env.workflow_scripts_path }}/js/test2.js')
            await runWorkflow({ github, context })
     
