name: trigger-determine-solution
on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: "name of the Solution in Dataverse environment"
        required: true
        default: MicaSolution
      environment_url:
        description: "http endpoint of your Dataverse environment"
        required: true
        default: "https://orgea394ded.crm.dynamics.com/"
      source_branch:
        description: "source branch"
        required: true
        default: main
      branch_to_create:
        description: "branch to create"
        required: false
        default: "init2"
      commit_message:
        description: "message to provide for the commit"
        required: true
        default: "init message"
env:
  workflow_scripts_path: .github/workflows/scripts

jobs:
  trigger-determine-solution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "solution_name: ${{ github.event.inputs.solution_name }}"
          echo "environment_url: ${{ github.event.inputs.environment_url }}"
          echo "source_branch: ${{ github.event.inputs.source_branch }}"
          echo "branch_to_create: ${{ github.event.inputs.branch_to_create }}"
          echo "commit_message: ${{ github.event.inputs.commit_message }}"
      - name: export-unpack-commit-solution
        id: export-unpack-commit-solution
        shell: pwsh
        env:
          # Workflows cannot be dispatched with the standard GITHUB_TOKEN, so we use a token that can
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
        run: |
          . ${{ env.workflow_scripts_path }}/pwsh/Test-Run2.ps1        
          Run-Workflow 
     
