name: trigger-deploy-tagged-solution
on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: "GitHub tag for solution-version to deploy"
      environment:
        required: true
        description: "GitHub environment name to deploy to"
        default: prod
env:
  workflow_scripts_path: .github/workflows/scripts

jobs:
  trigger-deploy-tagged-solution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - name: deploy-tagged-solution-to-environment
        id:  deploy-tagged-solution-to-environment
        shell: pwsh  
        env:
          # Workflows cannot be dispatched with the standard GITHUB_TOKEN, so we use a token that can
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
        run: |
          . ${{ env.workflow_scripts_path }}/pwsh/Test-Run-Deploy.ps1    
          
          $params = @{
              githubRef = '${{ github.ref }}'
              solution_name = '${{ github.event.inputs.solution_name }}'
          }
          Run-Workflow @params  
