name: trigger-determine-solution
on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: "name of the Solution in Dataverse environment"
        required: true
        default: MicaSolution
  pull_request:
    branches:
      - main
    paths:
      - src/**
  push:
    branches:
      - main
    paths:
      - src/**
  
        
env:
  workflow_scripts_path: .github/workflows/scripts


jobs:
 determine-solution-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: test2
        id: test2
        run: |
          . ${{ env.workflow_scripts_path }}/pwsh/Test-Run2.ps1
     
