name: trigger-determine-solution
on:
  pull_request:
    branches:
      - main
    paths:
      - src/**
  push:
    branches:
      - main
    paths:
      - src/**
env:
  workflow_scripts_path: .github/workflows/scripts

jobs:
  trigger-determine-solution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - name: determine-solution-build-deploy-test
        id:  determine-solution-build-deploy-test
        shell: pwsh  
        env:
          # Workflows cannot be dispatched with the standard GITHUB_TOKEN, so we use a token that can
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
        run: |
          . ${{ env.workflow_scripts_path }}/pwsh/Test-Run-Determine.ps1    
          
          $params = @{
              githubRef = '${{ github.ref }}'
              solution_name = '${{ github.event.inputs.solution_name }}'
          }

          Run-Workflow @params  
